name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm turbo run build --filter=apps/web...

      - name: Start server
        run: |
          pnpm --filter apps/web start &
          echo $! > server.pid
          npx wait-on http://localhost:3000
      - name: Playwright browsers
        run: npx playwright install --with-deps

      - name: Smoke
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: pnpm --filter apps/web test:smoke

      - name: Links
        if: always()
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: pnpm --filter apps/web test:links

      - name: Stop server
        if: always()
        run: kill $(cat server.pid) || true
